### ISSUE TITLE
Failed to hydrate store. Throwing away data from stogare

### ISSUE THREAD

**Issue by nastassiadanilova** [kuasha420/mst-persistent-store#2]
https://github.com/kuasha420/mst-persistent-store/blob/master/src/index.tsx#L108
It's really wrong practice to delete all the data from the storage. Just dangerous if we have client-only application and store the data that cannot be refetched from the server.
is it possible to apply partly key by key and remove only part of storage that invoke error?

**Comment by kuasha420** [comment]
Thanks for raising @nastassiadanilova !! Partial hydration is released in `v3.1.0`
