### ISSUE TITLE
onHydrate option

### ISSUE THREAD

**Issue by nastassiadanilova** [kuasha420/mst-persistent-store#3]
is it possible to implement onHydrate callback that can be provided to createPersistentStore options?
it's very useful as hydration is async and I faced a case when my actions right after the mounting were performed before the initial hydration from the localforage?

**Comment by smamun19** [comment]
Hello, I have also faced this similar issue. So opened a PR to address this. @kuasha420 please have a look :slightly_smiling_face:

**Comment by kuasha420** [comment]
Arghh, missed this one in my GH notification. Thanks @nastassiadanilova for raising and @smamun19 for the PR. I'll get this merged and released ASAP. Cheers all.

**Comment by kuasha420** [comment]
Released in `v3.1.0`
